FROM node:14.17.2

RUN mkdir -p /usr/src/app
RUN mkdir -p /usr/src/app/backend
#
WORKDIR /usr/src/app/backend

COPY package*.json ./
RUN npm update
RUN npm install --force
RUN npm rebuild bcrypt --build-from-source

COPY . .

ENV PORT=$PORT

CMD [ "npm", "run", "dev"]